version: "3.9"
services:
  postgres:
    container_name: database-server
    image: postgres:15.3
    environment:
      POSTGRES_DB: "db1"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"    

volumes:
  db-data: